#
# This module is provided as IBAMR_USE_FILE by IBAMRConfig.cmake.  It can
# be INCLUDEd in a project to load the needed compiler and linker
# settings to use IBAMR.
#

IF(NOT IBAMR_USE_FILE_INCLUDED)
  SET(IBAMR_USE_FILE_INCLUDED 1)

  # Update CMAKE_MODULE_PATH so includes work.
  SET (CMAKE_MODULE_PATH
    ${CMAKE_MODULE_PATH}
    ${IBAMR_CMAKE_DIRS})

  # Add compiler flags needed to use IBAMR.
  SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${IBAMR_C_FLAGS}")
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${IBAMR_CXX_FLAGS}")
  SET(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} ${IBAMR_Fortran_FLAGS}")
  SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${IBAMR_EXE_LINKER_FLAGS}")
  SET(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${IBAMR_SHARED_LINKER_FLAGS}")
  SET(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} ${IBAMR_MODULE_LINKER_FLAGS}")

  # Add include directories needed to use IBAMR.
  INCLUDE_DIRECTORIES(${IBAMR_INCLUDE_DIRS})

ENDIF(NOT IBAMR_USE_FILE_INCLUDED)
